Repository andela/mmdp_site, pull requests merged in 2019-04, with the labels that each got.

#121 MMDP-476 implement partnership type dropdown
  .codeclimate.yml
  client/__tests__/containers/dropdowns/partnershiptype.test.js
  client/__tests__/store/actions/dropdowns/partnership.type.test.js
  client/__tests__/store/saga/dropdowns/partnershiptype.saga.test.js
  client/__tests__/views/Dropdowns/dropdowns.views.test.js
  client/components/DropDowns/PartnershipType/index.js
  client/components/common/Form/DropdownForm/index.js
  client/constants/dropdowns/partnershipTypes.js
  client/constants/index.js
  client/containers/DropDowns/PartnershipType/index.js
  client/routes/index.js
  client/store/actions/dropdowns/partnershipType.js
  client/store/reducers/dropdowns/partnershipType.js
  client/store/reducers/index.js
  client/store/sagas/dropdowns/partnershipType.js
  client/store/sagas/saga.js
  client/utils/api.js
  client/views/DropDowns/PartnershipType/index.js
Labels: Finished

#118 MMDP-458 Implement source of funding dropdown
  client/__tests__/components/common/fundingForm.test.js
  client/__tests__/components/dropdowns/funding.test.js
  client/__tests__/containers/dropdowns/funding.container.test.js
  client/__tests__/containers/dropdowns/funding.form.test.js
  client/__tests__/store/actions/dropdowns/funding.actions.test.js
  client/__tests__/store/saga/dropdowns/funding.test.js
  client/assets/styles/events.scss
  client/components/DropDowns/SourceOfFunding/index.js
  client/components/DropDowns/SourceOfFunding/input.js
  client/constants/dropdowns/funding.js
  client/containers/DropDowns/SourceOfFunding/index.js
  client/containers/DropDowns/State/index.js
  client/index.js
  client/routes/index.js
  client/store/actions/dropdowns/funding.js
  client/store/reducers/dropdowns/funding.js
  client/store/reducers/index.js
  client/store/sagas/dropdowns/funding.js
  client/store/sagas/saga.js
  client/utils/api.js
  client/views/DropDowns/SourceOfFunding/index.js
  server/__tests__/helpers/dropdowns/funding.js
  server/__tests__/helpers/dropdowns/returnServices.js
  server/__tests__/tests/api/dropdowns/sourceOfFunding.spec.js
  server/constants/responseMessage.js
  server/index.js
  server/routes/api/dropdowns/fundingSource.js
  server/routes/index.js
  server/validation/dropdowns/funding.js
  server/validation/dropdowns/index.js
  server/validation/index.js
Labels: Finished

#114 MMDP-494 Organization Types Dropdown CRUD Operation
  client/__tests__/components/dropdowns/organizationTypes.test.js
  client/__tests__/containers/dropdowns/organizationTypes.test.js
  client/__tests__/store/actions/dropdowns/organizationTypes.test.js
  client/__tests__/store/saga/dropdowns/LGA.test.js
  client/__tests__/store/saga/dropdowns/organizationTypes.test.js
  client/__tests__/views/Dropdowns/organizationTypes.test.js
  client/components/DropDowns/OrganizationType/index.js
  client/components/common/Form/DropdownForm/index.js
  client/constants/dropdowns/organizationType.js
  client/containers/DropDowns/OrganizationType/index.js
  client/routes/index.js
  client/store/actions/dropdowns/organizationType.js
  client/store/reducers/dropdowns/organizationType.js
  client/store/reducers/index.js
  client/store/sagas/dropdowns/organizationType.js
  client/store/sagas/saga.js
  client/utils/api.js
  client/views/DropDowns/OrganizationType/index.js
  server/__tests__/helpers/dropdowns/organizationTypes.js
  server/__tests__/tests/api/dropdowns/beneficiaryType.spec.js
  server/__tests__/tests/api/dropdowns/organizationTypes.spec.js
  server/routes/api/dropdowns/organizationType.js
  server/routes/index.js
  server/validation/dropdowns/organizationDropdown.js
  server/validation/index.js
Labels: Finished

#119 MMDP 422 Implement crud api for ward dropdowns
  client/__tests__/actions/dropdowns/wards.actions.test.js
  client/__tests__/components/dropdowns/ward.test.js
  client/__tests__/containers/dropdowns/ward.container.test.js
  client/__tests__/reducers/dropdowns/wards.reducer.test.js
  client/__tests__/store/saga/dropdowns/ward.test.js
  client/components/DropDowns/Ward/index.js
  client/components/DropDowns/Ward/input.js
  client/constants/dropdowns/ward.js
  client/containers/DropDowns/Ward/index.js
  client/routes/index.js
  client/store/actions/dropdowns/ward.js
  client/store/reducers/dropdowns/ward.js
  client/store/reducers/index.js
  client/store/sagas/dropdowns/ward.js
  client/store/sagas/saga.js
  client/utils/api.js
  client/views/DropDowns/Ward/index.js
  server/__tests__/helpers/dropdowns/LGA.js
  server/__tests__/helpers/dropdowns/communities.js
  server/__tests__/helpers/dropdowns/ward.js
  server/__tests__/tests/api/dropdowns/ward.spec.js
  server/constants/responseMessage.js
  server/models/dropdowns/Community.js
  server/models/dropdowns/Ward.js
  server/routes/api/dropdowns/ward.js
  server/routes/index.js
  server/validation/dropdowns/ward.js
  server/validation/index.js
Labels: Finished

#113 MMDP-488 Manage Target Audience Dropdown options.
  .gitignore
  client/__tests__/containers/dropdowns/targetAudience.container.test.js
  client/__tests__/containers/dropdowns/targetAudience.form.test.js
  client/__tests__/store/actions/dropdowns/targetAudience.actions.test.js
  client/__tests__/store/reducers/dropdowns/targetAudience.reducers.test.js
  client/__tests__/store/saga/dropdowns/targetAudience.saga.test.js
  client/assets/styles/pages/_dropdown.scss
  client/components/DropDowns/TargetAudience/index.js
  client/components/common/Form/DropdownForm/index.js
  client/constants/dropdowns/targetAudience.js
  client/containers/DropDowns/TargetAudience/index.js
  client/routes/index.js
  client/store/actions/dropdowns/targetAudience.js
  client/store/actions/index.js
  client/store/reducers/dropdowns/targetAudience.js
  client/store/reducers/index.js
  client/store/sagas/dropdowns/targetAudience.js
  client/store/sagas/saga.js
  client/utils/api.js
  client/views/DropDowns/TargetAudience/index.js
  server/__tests__/helpers/dropdowns/targetAudience.js
  server/__tests__/tests/api/dropdowns/targetAudience.spec.js
  server/routes/api/dropdowns/targetAudience.js
  server/routes/index.js
  server/validation/dropdowns/targetAudience.js
  server/validation/index.js
Labels: Finished

#110 MMDP-452 Manage Impact Type Dropdown
  client/__tests__/components/dropdowns/ImpactType.test.js
  client/__tests__/containers/dropdowns/impactType.container.test.js
  client/__tests__/store/actions/dropdowns/impactTypes.actions.test.js
  client/__tests__/store/saga/dropdowns/impactType.saga.test.js
  client/assets/styles/events.scss
  client/components/DropDowns/ImpactType/index.js
  client/constants/dropdowns/impactTypes.js
  client/constants/index.js
  client/containers/DropDowns/ImpactTypes/index.js
  client/routes/index.js
  client/store/actions/dropdowns/impactTypes.js
  client/store/reducers/dropdowns/impactTypes.js
  client/store/reducers/index.js
  client/store/sagas/dropdowns/impactTypes.js
  client/store/sagas/saga.js
  client/utils/api.js
  client/views/DropDowns/ImpactType/index.js
  server/__tests__/helpers/dropdowns/impactType.js
  server/__tests__/tests/api/dropdowns/impactType.spec.js
  server/routes/api/dropdowns/impactType.js
  server/routes/index.js
Labels: Finished

#108 MMDP-403 Implements country dropdowns
  client/__tests__/components/dropdowns/__snapshots__/country.spec.js.snap
  client/__tests__/components/dropdowns/country.spec.js
  client/__tests__/containers/dropdowns/country.test.js
  client/__tests__/store/saga/dropdowns/country.saga.test.js
  client/__tests__/views/Dropdowns/country.test.js
  client/components/DropDowns/Country/index.js
  client/constants/dropdowns/country.js
  client/containers/DropDowns/Country/index.js
  client/containers/DropDowns/State/index.js
  client/routes/index.js
  client/store/actions/dropdowns/country.js
  client/store/reducers/dropdowns/country.js
  client/store/sagas/dropdowns/country.js
  client/store/sagas/saga.js
  client/utils/api.js
  client/views/DropDowns/Country/index.js
  package.json
  server/__tests__/helpers/dropdowns/country.js
  server/__tests__/tests/api/dropdowns/country.spec.js
  server/routes/api/dropdowns/country.js
  server/routes/index.js
  server/validation/dropdowns/country.js
  server/validation/index.js
Labels: Finished, feedback implemented

#127 MMDP-531 Implement truncate a dropdown model
  server/__tests__/helpers/dropdowns/returnServices.js
  server/__tests__/tests/api/dropdowns/trancateDropdowns.spec.js
  server/routes/api/dropdowns/truncateCollection.js
  server/routes/index.js
Labels: Finished

#128 MMDP-482 Allow admin to manage frequency option dropdown
  client/__tests__/containers/dropdowns/frequency.container.test.js
  client/__tests__/containers/dropdowns/frequency.form.test.js
  client/__tests__/store/actions/dropdowns/frequency.actions.js
  client/__tests__/store/reducers/dropdowns/frequency.reducer.test.js
  client/__tests__/store/saga/dropdowns/frequency.saga.test.js
  client/__tests__/utils/dropDowns/frequency.api.test.js
  client/__tests__/views/Dropdowns/frequency.view.test.js
  client/components/DropDowns/Frequency/index.js
  client/components/DropDowns/Frequency/input.js
  client/constants/dropdowns/frequency.js
  client/containers/DropDowns/Frequency/index.js
  client/routes/index.js
  client/store/actions/dropdowns/frequency.js
  client/store/reducers/dropdowns/frequency.js
  client/store/reducers/index.js
  client/store/sagas/dropdowns/frequency.js
  client/store/sagas/saga.js
  client/utils/api.js
  client/views/DropDowns/Frequency/index.js
  server/__tests__/helpers/dropdowns/frequency.js
  server/__tests__/tests/api/dropdowns/frequency.spec.js
  server/models/dropdowns/Frequency.js
  server/routes/api/dropdowns/Frequency.js
  server/routes/api/dropdowns/fundingSource.js
  server/routes/index.js
  server/validation/dropdowns/frequency.js
  server/validation/index.js
Labels: Finished

#135 MMDP-434 Implement manage thematic pillars dropdown options
  client/__tests__/components/common/ThematicPillarsForm.test.js
  client/__tests__/components/dropdowns/__snapshots__/country.spec.js.snap
  client/__tests__/containers/dropdowns/thematicPillar.container.test.js
  client/__tests__/containers/dropdowns/thematicPillar.form.test.js
  client/__tests__/store/actions/dropdowns/thematicPillars.test.js
  client/__tests__/store/saga/dropdowns/thematicPillar.test.js
  client/__tests__/utils/dropDowns/helpers.test.js
  client/__tests__/views/Dropdowns/thematicPillars.test.js
  client/assets/styles/pages/_dropdown.scss
  client/components/DropDowns/ThematicPillars/index.js
  client/components/common/Form/DropdownForm/index.js
  client/components/common/Form/ThematicPillarsForm.js
  client/constants/dropdowns/thematicPillars.js
  client/containers/DropDowns/ThematicPillars/index.js
  client/routes/index.js
  client/store/actions/dropdowns/thematicPillars.js
  client/store/reducers/dropdowns/thematicPillar.js
  client/store/reducers/index.js
  client/store/sagas/dropdowns/helpers.js
  client/store/sagas/dropdowns/thematicPillars.js
  client/store/sagas/saga.js
  client/utils/api.js
  client/utils/dropdowns/index.js
  client/views/DropDowns/ThematicPillars/index.js
  server/__tests__/helpers/dropdowns/thematicPillars.js
  server/__tests__/tests/api/dropdowns/thematicPillars.js
  server/constants/responseCodes.js
  server/models/dropdowns/ThematicPillarDropdown.js
  server/routes/api/dropdowns/thematicPillars.js
  server/routes/index.js
  server/validation/dropdowns/thematicPillars.js
  server/validation/index.js
Labels: Finished

#134 MMDP-14 manage user authentication for coordination matrix
  server/__tests__/tests/api/auth.spec.js
  server/routes/api/auth.js
  server/routes/index.js
  server/utils/mailer.js
  server/validation/auth/index.js
  server/validation/index.js
Labels: Finished

#132 MMDP-533: Bug fix for Edo State Approach.
  server/__tests__/tests/api/about/edoStateApproach.spec.js
  server/middleware/about.js
Labels: Finished

#131 MMDP-440 Implement sub-theme dropdown
  client/__tests__/actions/dropdowns/subTheme.actions.test.js
  client/__tests__/components/dropdowns/subTheme.test.js
  client/__tests__/components/dropdowns/ward.test.js
  client/__tests__/containers/dropdowns/subTheme.test.js
  client/__tests__/reducers/dropdowns/subTheme.reducer.test.js
  client/__tests__/store/saga/dropdowns/subTheme.test.js
  client/assets/styles/components/_button.scss
  client/components/DropDowns/SubTheme/index.js
  client/components/DropDowns/SubTheme/subThemeInput.js
  client/constants/dropdowns/subTheme.js
  client/containers/DropDowns/SubTheme/index.js
  client/routes/index.js
  client/store/actions/dropdowns/subTheme.js
  client/store/reducers/dropdowns/subTheme.js
  client/store/reducers/index.js
  client/store/sagas/dropdowns/subTheme.js
  client/store/sagas/saga.js
  client/utils/api.js
  client/views/DropDowns/SubTheme/index.js
  server/__tests__/helpers/dropdowns/subTheme.js
  server/__tests__/tests/api/dropdowns/subTheme.spec.js
  server/models/dropdowns/FocusArea.js
  server/models/dropdowns/SubTheme.js
  server/routes/api/dropdowns/subTheme.js
  server/routes/index.js
  server/validation/dropdowns/subTheme.js
  server/validation/index.js
Labels: Finished

#137 MMDP-446 Implement Focus Area Dropdown
  client/__tests__/components/dropdowns/focusArea.test.js
  client/__tests__/containers/dropdowns/focusArea.container.test.js
  client/__tests__/store/actions/dropdowns/focusArea.actions.test.js
  client/__tests__/store/reducers/dropdowns/focusArea.reducer.test.js
  client/__tests__/store/saga/dropdowns/focusArea.test.js
  client/assets/styles/Button/index.scss
  client/components/DropDowns/FocusArea/index.js
  client/components/DropDowns/FocusArea/input.js
  client/components/common/Button/DropdownActions.js
  client/constants/dropdowns/focusArea.js
  client/containers/DropDowns/FocusArea/index.js
  client/containers/DropDowns/ThematicPillars/index.js
  client/routes/index.js
  client/store/actions/dropdowns/focusArea.js
  client/store/reducers/dropdowns/focusArea.js
  client/store/reducers/index.js
  client/store/sagas/dropdowns/focusArea.js
  client/store/sagas/dropdowns/subTheme.js
  client/store/sagas/saga.js
  client/utils/api.js
  client/views/DropDowns/FocusArea/index.js
  server/__tests__/helpers/dropdowns/focusArea.js
  server/__tests__/tests/api/dropdowns/focusArea.spec.js
  server/__tests__/tests/api/dropdowns/thematicPillars.js
  server/models/resources/stakeholdersDirectory/ReturneeService.js
  server/routes/api/dropdowns/focusArea.js
  server/routes/api/dropdowns/thematicPillars.js
  server/routes/index.js
  server/validation/dropdowns/focusArea.js
  server/validation/index.js
Labels: Finished

#140 MMDP-547 Show number of entries in Target Audience
  server/__tests__/tests/api/dropdowns/targetAudience.spec.js
  server/routes/api/dropdowns/communities.js
  server/routes/api/dropdowns/targetAudience.js
Labels: wip

#141 MMDP-548 Fix changes made on the Pillars not being displayed on the website
  client/__tests__/components/dropdowns/__snapshots__/country.spec.js.snap
  server/models/Pillar.js
Labels: reviews needed
