Repository andela/mmdp_site, pull requests merged in 2019-03, with the labels that each got.

#74 MMDP-357 Fix login form style inconsistencies
  client/assets/styles/Login/index.scss
  client/components/LoginView/LoginView.js
Labels: Finished, bug fix

#62 MMDP-371 Allow guest access to list endpoints
  client/containers/Login/index.js
  server/__tests__/helpers/resources/research.js
  server/__tests__/tests/api/about/about.spec.js
  server/__tests__/tests/api/about/coordination.spec.js
  server/__tests__/tests/api/about/edoStateApproach.spec.js
  server/__tests__/tests/api/about/governorMessage.spec.js
  server/__tests__/tests/api/about/objectives.spec.js
  server/__tests__/tests/api/events.spec.js
  server/__tests__/tests/api/research.spec.js
  server/__tests__/tests/api/resources/document.spec.js
  server/__tests__/tests/api/resources/media.spec.js
  server/__tests__/tests/api/resources/report.spec.js
  server/__tests__/tests/api/stakeholdersDirectory.spec.js
  server/__tests__/tests/util/search.spec.js
  server/middleware/authenticate.js
  server/middleware/authorize/policies/cms/about.js
  server/middleware/authorize/policies/cms/events.js
  server/middleware/authorize/policies/cms/pillar.js
  server/middleware/authorize/policies/cms/resources.js
  server/middleware/authorize/policies/cms/stakeholders.js
  server/models/About.js
  server/models/Coordination.js
  server/models/EdoStateApproach.js
  server/models/GovernorMessage.js
  server/models/Objectives.js
  server/routes/api/Users.js
  server/routes/api/about.js
  server/routes/api/coordination.js
  server/routes/api/edoStateApproach.js
  server/routes/api/events.js
  server/routes/api/governorMessage.js
  server/routes/api/objectives.js
  server/routes/api/resources/document.js
  server/routes/api/resources/report.js
  server/routes/api/resources/research.js
  server/routes/index.js
  server/utils/search.js
Labels: Finished

#65 MMDP-229 Fix pagination and failing tests.
  client/__mocks__/fetchUserData.js
  client/__tests__/components/users/UserDetails.test.js
  client/__tests__/containers/users/viewUser.test.js
  client/__tests__/sagas/users/fetchUsersSaga.spec.js
  client/assets/css/users/index.scss
  client/containers/About/Objectives.js
  client/containers/Login/index.js
  client/containers/Users/ViewUsers.js
  client/store/reducers/users/fetchUsers.js
  server/__tests__/tests/api/research.spec.js
  server/__tests__/tests/api/resources/document.spec.js
Labels: Finished, feedback implemented

#80 Implement pagination for list media endpoint
  package.json
  server/routes/api/resources/media.js
Labels: Finished

#75 MMDP-380 Implement image upload functionality on about MMDP
  client/containers/About/AboutMMDP/index.js
  server/models/About.js
Labels: Finished

#72 MMDP-379 remove extra text field on Edo State Approach
  client/__tests__/components/resources/document.list.test.js
  client/__tests__/containers/EdoStateApproach.test.js
  client/__tests__/sagas/users/fetchUsersSaga.spec.js
  client/containers/About/EdoStateApproach.js
Labels: Finished

#60 MMDP-324 Implement delete media
  client/__tests__/components/Group/actionModal.test.js
  client/__tests__/components/Group/group.index.test.js
  client/__tests__/containers/Login/login.test.js
  client/__tests__/reducers/users/fetchUser.test.js
  client/__tests__/sagas/resources/archiver.specs.js
  client/__tests__/sagas/resources/deleteDocument.js
  client/__tests__/sagas/users/fetchUsersSaga.spec.js
  client/__tests__/store/actions/resources/document.action.test.js
  client/__tests__/store/reducers/resources/documents.reducer.test.js
  client/__tests__/store/reducers/resources/media.reducer.test.js
  client/__tests__/store/saga/resources/media.saga.test.js
  client/assets/styles/pages/_media.scss
  client/components/Group/ActionButtons.js
  client/components/Group/GroupItem.js
  client/components/Resources/Document/MediaList.js
  client/components/Resources/Media/MediaCard.js
  client/components/common/InvalidPage/index.js
  client/components/common/Modal/ActionModal.js
  client/constants/resources/media.js
  client/containers/About/Objectives.js
  client/containers/Resources/Document/DocumentList.js
  client/containers/Resources/Document/index.js
  client/containers/Resources/Media/MediaList.js
  client/containers/Users/ViewUsers.js
  client/store/actions/resources/document.js
  client/store/actions/resources/media.js
  client/store/reducers/index.js
  client/store/reducers/resources/document.js
  client/store/reducers/resources/media.js
  client/store/sagas/resources/archive.js
  client/store/sagas/resources/deleteDocument.js
  client/store/sagas/resources/media.js
  client/store/sagas/saga.js
  client/tests/components/Group/actionModal.test.js
  client/tests/components/Group/group.index.test.js
  client/utils/api.js
  server/__tests__/tests/api/research.spec.js
Labels: Finished

#81 MMDP-385 Fix inconsistent text and font style CMS
  client/assets/styles/_sidebar.scss
  client/assets/styles/events.scss
  client/assets/styles/main.scss
  client/containers/About/GovernorMessage/index.js
  client/containers/Sidebar/sidebarItems.js
  client/index.html
  client/views/About/index.js
Labels: Finished

#78 MMDP-381 Prevent logged in user from deleting or editing themselves.
  server/middleware/userMiddlewares.js
  server/models/resources/Research.js
  server/routes/api/Users.js
Labels: Finished, feedback implemented

#73 MMDP-361 Fix the width of "Upload report" and "Upload research" buttons
  client/assets/styles/_sidebar.scss
  client/assets/styles/components/_button.scss
  client/components/Resources/Report/ReportForm.js
  client/components/Resources/Research/ResearchForm.js
Labels: Finished, bug fix

#82 MMDP-401 Prevent manual access of admin paths on ui
  client/index.js
  client/routes/index.js
Labels: wip

#87 MMDP-512 Fix inability to delete user
  server/middleware/authorize/policies/user.js
  server/routes/api/Users.js
  server/routes/index.js
Labels: Finished

#69 MMDP-315 - Implements frontend for adding a stakeholder
  client/__tests__/actions/stakeholders.test.js
  client/__tests__/components/stakeholders/addBasicInformation.test.js
  client/__tests__/components/stakeholders/addBeneficiaryService.test.js
  client/__tests__/components/stakeholders/stakeholders.test.js
  client/__tests__/containers/stakeholders/addStakeholder.test.js
  client/__tests__/sagas/stakeholders/addStakeholder.test.js
  client/__tests__/store/reducers/stakeholders/addStakeholder.test.js
  client/__tests__/views/stakeholders/addBasicInfo.test.js
  client/__tests__/views/stakeholders/addBeneficiaryServices.test.js
  client/__tests__/views/stakeholders/stakeholderDirectory.test.js
  client/assets/css/users/index.scss
  client/assets/images/cancel-button-dark.png
  client/assets/images/group-2.png
  client/assets/styles/abstracts/_theme_variables.scss
  client/assets/styles/events.scss
  client/assets/styles/index.scss
  client/assets/styles/main.scss
  client/assets/styles/stakeholder.scss
  client/components/Stakeholders/addBasicInfo.js
  client/components/Stakeholders/addBeneficiaryServices.js
  client/components/Stakeholders/formHeader.js
  client/components/Stakeholders/formInputs.js
  client/components/Stakeholders/formLabels.js
  client/components/Stakeholders/stakeholders.js
  client/components/Stakeholders/textArea.js
  client/constants/stakeholderDirectory.js
  client/containers/Sidebar/sidebarItems.js
  client/containers/Stakeholders/addStakeholder.js
  client/containers/Stakeholders/stakeholdersList.js
  client/routes/index.js
  client/store/actions/stakeholders/stakeholders.js
  client/store/reducers/index.js
  client/store/reducers/stakeholders/addStakeholder.js
  client/store/sagas/saga.js
  client/store/sagas/stakeholders/addStakeholder.js
  client/utils/stakeholders.js
  client/views/Stakeholders/addBasicInfo.js
  client/views/Stakeholders/addBeneficiaryServices.js
  client/views/Stakeholders/stakeholderDirectory.js
  server/models/stakeholdersDirectory/BasicInformation.js
  server/models/stakeholdersDirectory/BeneficiaryService.js
Labels: wip

#85 MMDP-382 - Implement new db schema
  .github/PULL_REQUEST_TEMPLATE.md
  server/__tests__/helpers/stakeholdersDirectory/index.js
  server/__tests__/tests/api/resources/Stakeholders/ReturneeService.spec.js
  server/__tests__/tests/api/resources/Stakeholders/Stakeholders.spec.js
  server/__tests__/tests/api/stakeholdersDirectory.spec.js
  server/middleware/stakeholdersDirectory.js
  server/models/Dropdowns/AmountInvestedRange.js
  server/models/Dropdowns/BeneficiaryType.js
  server/models/Dropdowns/Community.js
  server/models/Dropdowns/Country.js
  server/models/Dropdowns/ImpactType.js
  server/models/Dropdowns/LGA.js
  server/models/Dropdowns/OrganisationType.js
  server/models/Dropdowns/PartnershipType.js
  server/models/Dropdowns/RegistrationStatus.js
  server/models/Dropdowns/SourceOfFunding.js
  server/models/Dropdowns/StaffStrengthRange.js
  server/models/Dropdowns/StakeholderAdress.js
  server/models/Dropdowns/StakeholderPartnership.js
  server/models/Dropdowns/State.js
  server/models/Dropdowns/TargetAudience.js
  server/models/stakeholdersDirectory/BasicInformation.js
  server/models/stakeholdersDirectory/BeneficiaryService.js
  server/models/stakeholdersDirectory/ReturneeService.js
  server/models/stakeholdersDirectory/Stakeholders.js
  server/models/stakeholdersDirectory/index.js
  server/routes/api/resources/Stakeholders/ReturneeService.js
  server/routes/api/resources/Stakeholders/Stakeholders.js
  server/routes/api/stakeholdersDirectory.js
  server/routes/index.js
  server/updates/0.0.1-stakeholders.js
  server/validation/index.js
  server/validation/stakeholdersDirectory/ReturneeServiceValidation.js
  server/validation/stakeholdersDirectory/StakeholderValidation.js
  server/validation/stakeholdersDirectory/index.js
Labels: Finished

#91 MMDP-409 Implement state dropdown options
  server/__tests__/helpers/dropdowns/state.js
  server/__tests__/tests/api/dropdowns/state.spec.js
  server/middleware/authorize/policies/cms/dropdowns.js
  server/routes/api/dropdowns/country.js
  server/routes/api/dropdowns/state.js
  server/routes/index.js
  server/updates/0.0.2-country.js
  server/validation/dropdowns/state.js
  server/validation/index.js
Labels: Finished

#90 MMDP-346 : As a user I want to view an updated 'Events' page on the website.
  package.json
  server/__tests__/tests/api/events.spec.js
  server/core/policies/cms/events.js
  server/index.js
  server/routes/api/events.js
  server/routes/index.js
  yarn.lock
Labels: Finished

#96 MMDP: Fix merge Conflicts
  server/__tests__/helpers/dropdowns/state.js
  server/__tests__/tests/api/dropdowns/state.spec.js
  server/__tests__/tests/api/resources/document.spec.js
  server/core/policies/cms/dropdowns.js
  server/middleware/authorize/policies/cms/dropdowns.js
  server/routes/api/events.js
Labels: Finished

#95 MMDP-410 Implement adding state dropdown
  client/__tests__/containers/dropdowns/state.container.test.js
  client/__tests__/containers/dropdowns/state.form.test.js
  client/__tests__/containers/stakeholders/addStakeholder.test.js
  client/__tests__/store/actions/dropdowns/country.actions.test.js
  client/__tests__/store/actions/dropdowns/state.actions.test.js
  client/__tests__/store/saga/dropdowns/country.saga.test.js
  client/__tests__/store/saga/dropdowns/state.test.js
  client/assets/styles/base/_utilities.scss
  client/assets/styles/components/_button.scss
  client/assets/styles/main.scss
  client/assets/styles/pages/_state.scss
  client/components/DropDowns/State/index.js
  client/components/Stakeholders/addBasicInfo.js
  client/components/Stakeholders/addBeneficiaryServices.js
  client/components/common/Form/DropdownForm.js
  client/components/common/Modal/ActionModal.js
  client/constants/dropdowns/country.js
  client/constants/dropdowns/state.js
  client/constants/index.js
  client/containers/DropDowns/State/index.js
  client/containers/Stakeholders/addStakeholder.js
  client/routes/index.js
  client/store/actions/dropdowns/country.js
  client/store/actions/dropdowns/state.js
  client/store/reducers/dropdowns/country.js
  client/store/reducers/dropdowns/state.js
  client/store/reducers/index.js
  client/store/sagas/dropdowns/country.js
  client/store/sagas/dropdowns/state.js
  client/store/sagas/saga.js
  client/utils/api.js
  client/utils/dropdowns/index.js
  client/views/DropDowns/State/index.js
  package.json
  server/__tests__/tests/api/dropdowns/state.spec.js
  server/__tests__/tests/api/resources/document.spec.js
  server/core/policies/cms/dropdowns.js
  server/models/dropdowns/State.js
  server/routes/api/dropdowns/state.js
  server/routes/api/events.js
  server/routes/index.js
  server/updates/0.0.1-deleteme.js
  server/updates/0.0.2-country.js
  server/updates/0.0.3-country.js
  server/validation/dropdowns/state.js
  yarn.lock
Labels: Finished

#99 MMDP-516 Fix same height and color on buttons
  client/assets/css/users/containers/user-containers.scss
Labels: Finished

#100 MMDP-396 Fix submit button
  client/__tests__/components/resources/research/__snapshots__/addResearch.spec.js.snap
  client/__tests__/views/resources/addResearchView.spec.js
  client/assets/styles/Button/index.scss
  client/components/Resources/Document/AddEditDocument.js
  client/components/Resources/Report/ReportForm.js
  client/components/Resources/Research/ResearchForm.js
  client/components/events/EventForm.js
  client/containers/About/AboutMMDP/index.js
  client/containers/Pillar/pillarFour.js
  client/containers/Pillar/pillarOne.js
  client/containers/Pillar/pillarThree.js
  client/containers/Pillar/pillarTwo.js
  client/containers/Resources/Document/MediaForm.js
  client/containers/Resources/Document/index.js
  client/containers/Resources/Report/ReportForm.js
  client/containers/Resources/Research/Addresearch.js
  client/containers/events/event.js
  client/utils/validations.js
Labels: Finished

#97 MMDP-220 Implement archiving/unarchiving of events on the server side
  server/__tests__/tests/api/events.spec.js
  server/middleware/repository/archiveHelper.js
  server/routes/api/events.js
  server/routes/index.js
Labels: Finished

#98 MMDP-517 Fixing empty views and displaying loaders
  client/assets/styles/events.scss
  client/components/Resources/Document/MediaList.js
  client/components/Resources/Report/ListReport.js
  client/components/Resources/Research/ListResearch.js
  client/components/events/EventsList.js
  client/containers/Resources/Media/MediaList.js
  client/containers/Resources/Report/ListReport.js
  client/containers/Resources/Research/ListResearch.js
  client/containers/events/eventsList.js
Labels: Finished

#102 MMDP-423 disable deleting of states assigned to records
  client/containers/DropDowns/State/index.js
  client/store/sagas/dropdowns/state.js
  server/__tests__/helpers/dropdowns/LGA.js
  server/__tests__/helpers/dropdowns/StakeholderAddress.js
  server/__tests__/tests/api/dropdowns/state.spec.js
  server/routes/api/dropdowns/state.js
Labels: Finished

#106 MMDP-500 Implement manage registration status dropdown
  client/__tests__/containers/dropdowns/status.container.test.js
  client/__tests__/containers/dropdowns/status.form.test.js
  client/__tests__/store/actions/dropdowns/status.actions.test.js
  client/__tests__/store/saga/dropdowns/status.test.js
  client/assets/images/trash_bin.png
  client/assets/styles/pages/_state.scss
  client/components/DropDowns/RegistrationStatus/index.js
  client/components/common/Form/DropdownForm.js
  client/components/common/Form/regDropdownForm.js
  client/constants/dropdowns/statuses.js
  client/containers/DropDowns/RegistrationStatus/index.js
  client/routes/index.js
  client/store/actions/dropdowns/statuses.js
  client/store/reducers/dropdowns/status.js
  client/store/reducers/index.js
  client/store/sagas/dropdowns/status.js
  client/store/sagas/saga.js
  client/utils/api.js
  client/views/DropDowns/RegistrationStatus/index.js
  server/__tests__/helpers/dropdowns/Stakeholder.js
  server/__tests__/helpers/dropdowns/status.js
  server/__tests__/tests/api/dropdowns/status.spec.js
  server/routes/api/dropdowns/registrationStatus.js
  server/routes/index.js
  server/validation/dropdowns/status.js
  server/validation/index.js
Labels: Finished

#103 MMDP-220 Implement archiving/unarchiving events on the client side
  client/__tests__/actions/events.actions.test.js
  client/__tests__/containers/events/archiveEvent.test.js
  client/__tests__/reducers/events/archiveEvents.reducer.test.js
  client/__tests__/sagas/events/archiverEvents.specs.js
  client/assets/styles/index.scss
  client/components/events/EventCard.js
  client/constants/events.js
  client/containers/events/ArchiveEvent.js
  client/store/actions/events/event.js
  client/store/reducers/events/archiveEvents.js
  client/store/reducers/index.js
  client/store/sagas/events/archiveEvents.js
  client/store/sagas/saga.js
  client/utils/events.js
Labels: Finished

#107 MMDP-416 : LGA Dropdown CRUD operation
  .codeclimate.yml
  client/__tests__/components/dropdowns/LGA.test.js
  client/__tests__/containers/dropdowns/LGA.test.js
  client/__tests__/store/actions/dropdowns/LGA.test.js
  client/__tests__/store/saga/dropdowns/LGA.test.js
  client/__tests__/utils/dropDowns/LGA.test.js
  client/__tests__/views/Dropdowns/LGA.test.js
  client/components/DropDowns/LGA/index.js
  client/components/DropDowns/PartnershipType/index.js
  client/components/DropDowns/State/index.js
  client/components/common/Form/DropdownForm/index.js
  client/constants/dropdowns/LGA.js
  client/containers/DropDowns/LGA/index.js
  client/containers/DropDowns/RegistrationStatus/index.js
  client/routes/index.js
  client/store/actions/dropdowns/LGA.js
  client/store/reducers/dropdowns/LGA.js
  client/store/reducers/index.js
  client/store/sagas/dropdowns/LGA.js
  client/store/sagas/saga.js
  client/utils/dropdowns/LGA.js
  client/views/DropDowns/LGA/index.js
  server/__tests__/helpers/dropdowns/LGA.js
  server/__tests__/tests/api/dropdowns/LGA.spec.js
  server/models/dropdowns/Ward.js
  server/routes/api/dropdowns/LGA.js
  server/routes/index.js
  server/updates/0.0.2-deleteme.js
  server/validation/dropdowns/LGA.js
  server/validation/index.js
Labels: Finished, feedback given, feedback implemented

#117 MMDP-395 Fix highlights on sidebar submenu
  client/__tests__/components/Resources/research/listResearch.spec.js
  client/__tests__/components/Sidebar/sidebar.index.test.js
  client/__tests__/components/resources/report/listReports.spec.js
  client/assets/styles/_sidebar.scss
  client/components/Resources/Document/TopBar.js
  client/components/Resources/Media/MediaCard.js
  client/components/Resources/Report/ListReport.js
  client/components/Resources/Research/ListResearch.js
  client/components/Sidebar/TitleContent/index.js
  client/components/common/AddNewButton/index.js
  client/containers/Resources/Document/DocumentList.js
Labels: Finished, bug fix, feedback given, feedback implemented
